### ISSUE TITLE
Multiple calls to the variable $db

### ISSUE THREAD

**Issue by hu9osaez** [Sama34/OUGC-Profile-Fields-Categories#1]
Inspecting the code of this plugin, I have seen on line [#163](https://github.com/Sama34/OUGC-Profile-Fields-Categories/blob/master/Upload/inc/plugins/ougc_profiecats.php#L163) multiple calls to the global variable $db.

Check whether it is or is wrong.

Greetings :v:

**Comment by Sama34** [comment]
lol, thanks for pointing out. I have pushed a fix.
